### ISSUE TITLE
Prophecy rule

### ISSUE THREAD

**Issue by SamuelLu** [NeverSinkDev/NeverSink-Filter#102]
Line 4788:Unable to parse for Prophecy rule : No prophecies found matching "xxx"

**Comment by Tobnac** [comment]
This sounds a lot like you made a mistake when editing the filter. All of the default filters work just fine. You (or whoever you got that filter from) probably added the "xxx" into the Prophecy tierlist by accident and, since a prophecy with such a name doesnt exist, causes the game client to not accept the filter.
