### ISSUE TITLE
Sai is matching Saint's Hauberk

### ISSUE THREAD

**Issue by jozefspisiak** [NeverSinkDev/NeverSink-Filter#104]
I was doing my Maraketh Steel achievement with help filterblade I added bases I was missing with custom color. I was surprised why I was getting this armor marked and thought I did something wrong when I realized it is matching first letters probably. Not sure if it is a bug in the filter or in the game. Here is the filter I was using: http://www.filterblade.xyz/#ikZwGgfv800o

Items in question: https://pathofexile.gamepedia.com/Sai and https://pathofexile.gamepedia.com/Saint%27s_Hauberk

**Comment by jozefspisiak** [comment]
Also https://pathofexile.gamepedia.com/Saintly_Chainmail

**Comment by Tobnac** [comment]
This is how the PoE filters work. The string checks only check if the item baseType CONTAINS the string from the filter. This is why filtering for "Sai" also accepts any other items with Sai in their name. If you were to add "a" as a name it would accept all items that have an "a" in their name,

This isnt exactly a bug on either side, but I understand the problem.
You should be able to add a Class-filtering rule, set the classes to Dagger and add baseType filtering to Sai. Because only the actual Sai is a dagger. Or you could try to limit it with Width/Height filtering.

**Comment by jozefspisiak** [comment]
Great, thanks for explanation :) will keep it in mind for future, I got the achievement now, so no need to keep it in my filter anymore.
