### ISSUE TITLE
[Bug] Maps incorrectly displayed/no sound played

### ISSUE THREAD

**Issue by Ydoum** [NeverSinkDev/NeverSink-Filter#108]
Hey,

Just quick note. I just ran Oba's with the latest release of the filter (for synthesis league) and I noticed an issue with a map drop.

As an example I found 2x tier 7 academy maps. One of them was treated as an "unimportant" item, being shown with small font, small border and with no sound played, the other one was correctly displayed with the sound playing. One was ilvl 80, the other ilvl 84.

Running semi-strict filter.

Could you please take a look into it?

**Comment by Ydoum** [comment]
screenshot link for reference: https://muody.home.pl/pub/screenshot-0029.png

**Comment by Tobnac** [comment]
This seems correct to me.

The filter has a "map outleveling" system that causes low tier maps to get highlight and sound when they're "new", i.e. when you're level 70 and just reached maps - while also giving that same tier 1 map basically no highlight/sound when it drops in a very high tier map. Because who cares about some tier 1 map when you're running tier 15+ maps?

This is done via the ItemLevel and the actual tier of the map and affects all maps that are 10+ tiers below the map that they dropped in.

ItemLevel 80 + MapTier 7 = a tier 7 dropped in a tier 13 map -> 6 level difference -> highlight
ItemLevel 84 + MapTier 7 = a tier 7 dropped in a tier 17 map -> 10 level difference -> no highlight

This itemLevel can of course be different from the actual map tier that you're currently in by dropping from +5 level strongboxes or rares/uniques, but its the only identifier we have access to with a filter.
