### ISSUE TITLE
SlipperyJim_12leveling.mp3 missing from preset

### ISSUE THREAD

**Issue by spaelling** [NeverSinkDev/NeverSink-Filter#109]
I had that file at some point. Tried a reset filter, set the slippery jim preset, and downloading all filter levels. The regular level needs that file. For now I just renamed one of the other files.

**Comment by Tobnac** [comment]
We looked at this multiple times now and never really had the problem ourselves. It just seems like our server hoster sometimes has some hiccups and won't send all requested files. We improved our file request system multiples times to verify the requested file successfully arrived and to retry if it didnt. I hope this solved problems of these kind for now. Let me know if you still have problems. Those might even be based on your location since the one and only hoster is set in central EU, causing slow/bad responses for people in e.g. South America.
