### ISSUE TITLE
Unable to parse parameter for Prophecy rule

### ISSUE THREAD

**Issue by jan-car** [NeverSinkDev/NeverSink-Filter#122]
Hi, I hope this is the right channel for this :-).

I get the following error message when I try to load my customized filter (done via Filterblade.xyz):
`Failed to load Item Filter: Line 5214: Unable to parse parameter for Prophecy rule: No prophecies found matching "The Emperor's Trove"`

The filter in question can be found here:
http://filterblade.xyz/?profile=DangerMcCool&saveState=VERYSTRICT&platform=pc

Here's the relevant section from the filter file:
```
Show # $tier->t1 $type->currency->prophecy
	Class Currency
	BaseType "Prophecy"
	Prophecy "Cleanser of Sins" "Fated Connections" "Monstrous Treasure" "The Great Leader of the North" "The Queen's Sacrifice" "Trash to Treasure" "Wind and Thunder" "The Emperor's Trove" "Twice Enchanted" "Living Fires" "Vaal Winds" "The Jeweller's Touch" "Darktongue's Shriek"
	SetFontSize 45
	SetTextColor 130 25 255 255             # TEXTCOLOR:	 Blessing
	SetBorderColor 130 25 255 255           # BORDERCOLOR:	 Breach
	SetBackgroundColor 255 255 255 255      # BACKGROUND:	 T0 Drop
	PlayAlertSound 6 300                    # DROPSOUND:	 T0 Drop
	PlayEffect Red
	MinimapIcon 0 Red Star
```

Any idea what could be the problem? The prophecy exists, so I'm not sure what exactly goes wrong.

Thanks!

**Comment by Saiasanc** [comment]
I am by no means an expert here, but if you look at the wiki here:
https://pathofexile.gamepedia.com/The_Emperor%27s_Trove

It shows under Acquisition "Drop Disabled" and there is a note under the Version changes section for 2.3.1 of:
"Navali will no longer offer The Emperor's Trove. The original design intent was that only one could be used per run. We can't prevent multiple of these prophecies applying, and that ruins the intended rewards of the Labyrinth."

This leads me to believe that you can no longer obtain that prophecy. Therefore the reason for the error since the prophecy no longer exists.

I could be wrong. But that's what I take away from it just by examining the wiki in detail.

--Sai

**Comment by jan-car** [comment]
Ah, that makes a lot of sense, I didn't catch that important little detail when looking at the Wiki page.
Maybe this issue still has some relevance though, because the error only occured after used the auto-sort function for the divination card section.
My assumption is that "The Emperor's Trove" card, even though it can't drop anymore, still has listings in Standard and therefore is put into the list, causing the error.
If I remove it by hand afterwards, the error disappears (and is promptly replaced by a similar error about the "Gratuitous Master" Prophecy).
I will just refrain from using the auto-sort method for prophecies, but maybe it still was worth reporting.
Many thanks!

**Comment by NeverSinkDev** [comment]
I'm going to add an "exclusion list" in one of the upcoming updates on FilterBlade/PolishZ to address this issue and/or contact GGG about that.

**Comment by NeverSinkDev** [comment]
Should be fixed.
