### ISSUE TITLE
Add SSL rewrite for filterblade.xyz

### ISSUE THREAD

**Issue by m1ckswagger** [NeverSinkDev/NeverSink-Filter#123]
Hi,

I am always just entering the url [filterblade.xyz](http://filterblade.xyz) in web browser and defaults to **HTTP** and I did not even realize you support **HTTPS**.

I don't think the PoE OAuth2 mechanism is faulty, and the PoE website uses **HTTPS** for authentication. But I still get a bad feeling when using it over **HTTP**.

Since I found out today you issue ```Letsencrypt``` certificates for [https://filterblade.xyz](https://filterblade.xyz), could you add a port 80 rewrite rule to enforce **HTTPS**?

Thank you

**Comment by NeverSinkDev** [comment]
There's a problem. When we designed the local saves for filterblade, we didn't know that the browser local storage is different for www/non-www/https/non-https URIs.

The resulti is that dozens or hundreds of thousands of local saves are currently spread across different versions... 

That's why we currently don't want to add a redirect. At least for now.

**Comment by NeverSinkDev** [comment]
I'm going to close this for now. Long-term we might deprecate the local saves or add a date in the future, where we'll force the redirect

**Comment by Dav1dde** [comment]
@NeverSinkDev to bring this up again, especially with the option to log into PoE now, maybe display a red warning with a migration path if you're on the http site not https.
