### ISSUE TITLE
Quality rare items not showing

### ISSUE THREAD

**Issue by Krayone** [NeverSinkDev/NeverSink-Filter#124]
Hello,

Two times I found a quality items chest in delve and they drop 30% quality rare items that are hidden by filter. One time in strict an one time in semi-strict mode I think.
I know those items with quality under 20% are usualy showing cause I make chaos recipes at league starting.

Thanks for all your precious grat work.

**Comment by Krayone** [comment]
In fact quality item over 20% seems to be hidden by filter.
Tested with a white armor of 30% that not show anywhere, but I know rare item don't show too.

With loot we have actually we can pass near valuable items with quality, this is much worse than what I expected at start.

**Comment by NeverSinkDev** [comment]
It's not explicitly hidden. They're just not highlighted. 

The filter has 2 rules to treat 20% items.

1) There's a rule for items over 28% quality (because 28% can be achieved with Hillock). However, the item has to have a high itemlevel and a good droplevel (good base). 

2) There's a disabled rule for 20% quality rare items, that can be enabled via FilterBlade or manual editing. This rule is currently set to EXACTLY 20%. In the upcoming update I'll change it to >=20%.
