### ISSUE TITLE
Can't Say I'm a Fan of E.g. Storm Prison Dropping Like it's an Exalt Because it Shares a Base with a Valuable Unique

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#148]

**Comment by AkumaNoTsubasa** [comment]
You can edit the filter to your own pace. Since a filter can not tell in before what item the base is, you need to evaluate if you handle the item for the lower or the higher base and I wanna bet, if you'd miss the high value base, because Neversink would treat it like a low item, you would be more mad.

**Comment by dsnvwlmnt** [comment]
Actually it was my mistake, I got confused with a previous coloring. Looks like multibase drop with a special coloring, not like exalts. My bad.
