### ISSUE TITLE
Switching Sound Packs with Existing Filters Would be Nice

### ISSUE THREAD

**Issue by dsnvwlmnt** [NeverSinkDev/NeverSink-Filter#165]
I was very surprised and saddened to find you can't just switch to a different Sound Pack with an existing filter. Who would restart their filter from scratch at this point?

I realize this may be an implementation nightmare, but perhaps an opportunity for refactoring, or for a Filterpolish-like script that simply does a search and replace.

**Comment by NeverSinkDev** [comment]
You can do that by going to Style->Sounds and switching the sounds to a different community sound. This requires 14 clicks instead of 2, but should still be easy enough.

This is more than an implementation nightmare sadly. Sound packs are based on presets, which are an exception to the save load system and are already causing a lot of trouble.

It's been on a drawing board several times and exchangeable presets requires in a complete rework of the save/load system, combined with an insane migration script.

I'm not saying that's won't happen, but unless there will be *pressing* reason to address that, I'd rather focus our current filterblade development power on... less suicidal projects.
