### ISSUE TITLE
Were the Transmutation and Chromatic orb drop sounds changed?

### ISSUE THREAD

**Issue by rushtothesun** [NeverSinkDev/NeverSink-Filter#200]
Their drop sound is now the same as Chaos orbs which is kinda strange.

**Comment by rushtothesun** [comment]
Blacksmith's Whetstone is also making the Chaos orb drop sound

**Comment by Npyusystem** [comment]
I have the same issue, and did some testing.
The problem is not on the filter's side. It's on the game's side (if that makes sense).
I edited the filter manually to display the whetstones and the transmutes in various size, colour and sounds. And no matter what change I make, the game will display them with the same size, colour and chaos sound, ignoring all settings made in the filterblade tool.

Chromatics on the other end, are set to do a chaos sound and that can be edited and removed normally.

So that's really wierd.
It looks like the game is overriding the settings regarding specifically whetstones and transmutes.

**Comment by Npyusystem** [comment]
Oh Actually, I figured out (feeling a bit stupid in the process) that this override comes from the "leveling" part of the filters.
Because after you get in level 65+ areas, the whetstones and transmutes behave normally.

Still not sure if the chaos sound for those orbs are intended.
But if anyone wants to look closer at it, it's gonna be in the leveling section of the filter.

**Comment by NeverSinkDev** [comment]
It was for only for leveling.

Still: Removed the sound in the coming update.
