### ISSUE TITLE
suggestion: stricter divination card filtering

### ISSUE THREAD

**Issue by Xebtria** [NeverSinkDev/NeverSink-Filter#21]
remove most of the worthless divination cards (I'd say like the T5 and T4 in your filter) from at least the strict filter, maybe even the semi strict.

**Comment by NeverSinkDev** [comment]
Hi,

I might disable T5 from strict, though I don't see a major problem with them yet, because they don't cause a sound and are rare enough.

I will however, definitely not disable T4. Quite a lot of them are decent, the economy fluctuates and they're also the failsafe for new patches (all unclassified cards are T4 by default). I might consider removing their sounds in uber-strict if the demand is high enough.

Thank you for the input and the suggestion though.

Closed.
