### ISSUE TITLE
Quick question?

### ISSUE THREAD

**Issue by KingKatura** [NeverSinkDev/NeverSink-Filter#214]
I notice that your github hasn't been updated since last month almost, But i notice the pathofexile filter list was updated today. So are you just updating it their now or was it just added to their recently? I didn't even notice the item filter tab at poe.com but i usualy check here first.

**Comment by Tobnac** [comment]
- PoE filter ladder: Updated automatically to adapt to economy every few hours.
- FilterBlade: Has both the auto-updated version as well as the manual "stable" version.
- GitHub: Only has the stable version. There used to be auto-updated versions on GitHub too but they were removed because the git history just became too long to work with.

All of these versions are fine to use, the auto-updated ones just have more up-to-date tierlists for the changing economy.

**Comment by KingKatura** [comment]
That i wasn't aware of thank you. So its best to probably use filter blade eh? I never cared for it because yours were the only ones i used other than my own which i got lazy so... Thanks again.
