### ISSUE TITLE
Leveling with the ubar strict filter 4.5

### ISSUE THREAD

**Issue by TerohsLab** [NeverSinkDev/NeverSink-Filter#23]
Hey Neversink

I'm leveling a new char right now and the ubar strict has always been my choice in mapping since you introduced it. I used it leveling this char too.

I have a few observations i want to share here

Since forever

* If you use the the ubar strict filter while leveling, i personally assume the user has twink gear to use.

Which means : weapon slots are fixed with your leveling weapon, boots are wanderlust, helm is goldrim, amulet is karui ward, belt is either wurm's molt, the magnate or meginords and the armor slot is tabula rasa, briskwrap or foxshade in the first 50 levels.

So all the items in those slots you show are irrelevant to strict / ubar strict filter users if they don't yield a chromatic or jeweler orbs.

I would personally just show rings, gloves, belts and to some extent, helms at the right ilvl while leveling with strict filters ( besides the usual recipies like chromes and jewelers )

* You need portal scrolls while leveling

Would just be nice to see portal scrolls while leveling to lvl 40-50,  but thats again personal preference i guess. Just takes so much time walking to the vendor, selling transmutes for wisdom, then rebuy portal scrolls.

* Stocking up on chromatic items while leveling, because you don't pick anything else up

Pretty self explanatory : I usually loot up chromatics, while leveling, since there is nothing else to pick up if i'm twinked. Would be nice to keep the "big" chromatics in the filter for a little longer.

Since 4.5

* 20q armors/weapons have no place in the ubar filter, even if they are ilvl capped at 60
* Why hide blue jewels? Probably comes down to personal preference, but its just 1 id away from a good base to use while leveling or even better, a good regal base.

**Comment by NeverSinkDev** [comment]
Hey,

All filters are identical when it comes to leveling, aside from a few details, where I had no choice ( There's no way to show wisdom/portals for just levels X-Y, it's an off/on switch ). 

I _might_ one day, redesign the filters to have different strictness for leveling, however for now, considering how fast leveling is and considering the fact that the item quantity is fairly low while leveling, I won't increase the code complexity and invest the time (since it's quite a lot of work) into it.

Also it's ub_e_r, not ubar.

Best regards,
NeverSink
