### ISSUE TITLE
Presets are not applied correctly to existing filter

### ISSUE THREAD

**Issue by DeBourgh** [NeverSinkDev/NeverSink-Filter#233]
Hi NeverSink and DevTeam,

preparing / experimenting with the current online version of filterblade.xyz and found the Presets-Feature cool and interesting.

However, in a simple test I tried to apply my newly created Preset, which was just a Tabula-Rasa-Style with two new Currency Tiers (one for all Exalted Orbs, one for Mirror).
The Preset is now in a state were I can remove it again (so I guess it was applied successfully) but the changes are not actually fully applied.
- The Exalted Orbs have the same style as before (which looks like a bug)
- The Mirror o. Kalandra on the other hand was changed accordingly (looks as expected).

Maybe it works as intended but the UI does not really tell me that there was either an issue when applying or that I am not allowed to do that stuff.

It looks like a bug since I am expecting something else from this feature.

What data would you need from me?

Have a nice evening. Erik

**Comment by Tobnac** [comment]
Hello Erik,

this sounds like an issue we resolved a couple days ago. Can you verify that this is still a problem today?
If so, can you send me the name of your account and preset(s) that have the issue so I can take a look at it myself?

**Comment by DeBourgh** [comment]
Yes, it seems to be an issue still.
My account name is Shounbourgh. "erik-std2" is the loaded filter (predondition) and there is a Preset named "[CURRENCY-Normal] Shounbourgh-1". When I apply it, the settings seem not to be applied after looking into Customize-Tab.

bb

**Comment by DeBourgh** [comment]
jeah, changed it

**Comment by Tobnac** [comment]
Wait, what are you trying to do?
So you have the SAVE-STATE with Ex and Mirrors being this brighter blue, right?
Then you have the PRESET with Ex and Mirrors being a darker blue.
And when you add the preset into your saveState, you expect these items to receive the darker blue from the preset and overwrite the bright blue from the saveState, is that correct?

Preset's have less priority than your own saveState changes.
If you want to use the preset colors, you have to not have any changes in your saveState.

Its a little difficult to achieve this now, since resetting might just save that reset in order to still overwrite the preset.
Try removing the preset(s) first. Save and Load the save. Then, reset the rules where you want the preset present. Save and Load. Then, add the preset.
