### ISSUE TITLE
Unable to parse

### ISSUE THREAD

**Issue by Y161537** [NeverSinkDev/NeverSink-Filter#259]
![Image_1712281490109](https://github.com/NeverSinkDev/NeverSink-Filter/assets/58110931/cd87aef1-f3b5-4a6e-a2c1-f84c3ce2d74a)
"Flaring Allflame Ember of(Breachlords"

Have a problem

**Comment by Tobnac** [comment]
You mentioned this on discord too, right?
Either way: Make sure you're using the newest version.
Sadly I presume the Chinese version of the game did not receive patch 3.24.0b yet, while the filter is already up-to-date for that, so you might need to use an older version from GitHub until your game gets the update.
Feel free to re-open or bring it up on discord again if that isnt the problem here.
