### ISSUE TITLE
Feature request: increased avian content

### ISSUE THREAD

**Issue by barde** [NeverSinkDev/NeverSink-Filter#34]
Pretty sure this gorgeous filter needs more birds!

🐦🐦🐦🐦🐦🐦🐦🐦

**Comment by NeverSinkDev** [comment]
This is an excellent suggestion!

I've included the following changes to the 5.0 version:

- All item labels will start with "Bird-"
- All bosses will be filtered and replaced with Garukhan, because she kinda looks like a bird ( https://web.poecdn.com/public/news/2017-06-05/Garukhan.jpg )
- All itemfilter sounds will make chirp-noises

Closed, because the evidence for the need for bird-action is non-debatable!
