### ISSUE TITLE
New Chance items not appearing?

### ISSUE THREAD

**Issue by moglad** [NeverSinkDev/NeverSink-Filter#46]
I'm still getting leather belts show up instead of Glorious plates, Close helmets, etc.

**Comment by NeverSinkDev** [comment]
The general chancing entry is hidden starting with the semi-strict filter and upwards. This is intended, because chancing is widely considered to be not time-efficient and there's no clear powerful chancing base, such as skyforth anymore (skyforth is not quite as useful in the life meta anymore)

If you want to enable it, I recommend using: http://filterblade.xyz/ 

Closed.
