### ISSUE TITLE
Red maps not making sound when dropping

### ISSUE THREAD

**Issue by sternburger** [NeverSinkDev/NeverSink-Filter#60]
My red maps are not making a sound when they drop, some guardians make a sound but almost all other red maps do not.

**Comment by NeverSinkDev** [comment]
There's currently a bug ingame that "swallows" some sounds, if the environment is too noisy. It has nothing to do with filters. Set the Channel count under audio settings to "High". This somewhat helps.

In the filter: All red maps are configured to have a sound ( www.FilterBlade.xyz -> you can check this out ). 

Otherwise, there's nothing I can do.
