### ISSUE TITLE
Chromatic recipe not highlighted

### ISSUE THREAD

**Issue by axelsword** [NeverSinkDev/NeverSink-Filter#62]
![chromatic-recipe](https://user-images.githubusercontent.com/37154132/37108124-1bf621b0-222e-11e8-8c97-2f4bf0537a9f.png)

Can you please make chromatic recipe stand out?
Using NeverSink 5.6 Bestiary filter

**Comment by NeverSinkDev** [comment]
Currently rare evaluation has priority over RGB highlighting. This is due to the complexity of the rare evaluation section. It'd require over a thousand additional lines and would decrease maintainability and possibly even performance. I'm considering doing some improvements in the future, but currently this is intended.
