### ISSUE TITLE
Skyforth not marked as high tier

### ISSUE THREAD

**Issue by blainicus** [NeverSinkDev/NeverSink-Filter#74]
Very simple. Dropped a skyforth and it was highlighted as a second lowest tier unique, slightly above normal, where it should be white highlighting.

**Comment by NeverSinkDev** [comment]
Q: I've found valuable [insertrandomunqiue] and it's not highlighted!

A: Filters can't distinguish between different uniques, only between basetypes. I can either highlight ALL uniques of a certain basetype or non.

If a single basetype has 2+ uniques - there's no way to implement the variation into the filter.

Example: a xoph's heart amulet is an "Amber Amulet". There are 2 unique amber amulets: "xoph's heart" and "the anvil". Xoph's heart is very expensive, but very very rare. I can either highlight both or highlight neither. In some cases, I give those uniques a T2 highlighting. 

However, especially in cases with league-specific uniques, I prefer not giving them any highlight. I'm afraid you just have to check those manually. Some of the further cases where this problem exists are Goathide boots, all jewels, leather belts in nemesis maps etc.

This does not apply to boss-specific drops. I see no reason to give those a T2 highlight, since you're expecting a drop anyway and it'll be wrong in all other times.

**Comment by blainicus** [comment]
Ok, thanks for checking my post bro. Appreciate what you do!!
