### ISSUE TITLE
Loreweave rule doesn't override unique rules?

### ISSUE THREAD

**Issue by Megaddd** [NeverSinkDev/NeverSink-Filter#81]
Filter setting set: https://i.imgur.com/Z2yg0FW.png
in-game looks like any other unique: https://i.imgur.com/uGuX0B6.png

Filter in question: http://www.filterblade.xyz/#uS9XSTCrjPd4

Am I just missing something or is this legitimately not working?

**Comment by Tobnac** [comment]
(We talked about this via Discord, so I'm gonna send a recap here too so people dont get confused:)

The problem in this case was that there was a custom unique tier that contains bad unique bases (which are a LOT, including rings). And this custom tier always has the top priority, while the loreweave rule is right below T1, T2 and multibase, meaning that the rings will be caught by the custom tier with all the trash uniques and wont get the additional highlight.

We're gonna have to see how we'll handle this situation, since its not exactly obvious whether someone wants loreweave to have priority over custom tiers or vise versa.

**Comment by NeverSinkDev** [comment]
The loreweave recipe (unique rings) has received a default highlight in the filter.

We intend to improve on the economy tiering implementation in the future, but the current implementation covers most use cases.
