### ISSUE TITLE
filterblade: make the sounds a normal drop down (like the styles) instead of having them as a preset

### ISSUE THREAD

**Issue by Xebtria** [NeverSinkDev/NeverSink-Filter#84]
I cannot do the following:

- select a sound style (via presets) like zizaran
- do some changes in the filter according to my needs
- then figure out I hate zizaran and select a different sound style (e.g. mathil)

the reason is, sound styles are presets, and you cannot change the presets once you've selected/executed them.

if I do some changes to the filter and then figure out I want a different sound set, I have to completely reset my filter, then change the sound set, and then do all the changes I've done after that again. I almost can guarantee I won't remember every single change I've done to the filter, so it would be nice if we could select the sound style similar to the color style (via a dropdown) instead of it being a preset, so we can change the sound style even after we've done changes to the filter.

**Comment by Tobnac** [comment]
That was our initial plan too, but the problem is that those community sound presets are PRESETS. And the dropDowns are for actual filter files. Those behave very differently.
Also: What you are wanting to do is not possible, no matter how the UI looks - presets that are applied onto an already edited filter can (in this specific case: "will") cause massive bugs. I recommend you check out the "Style" tab on FilterBlade. Selecting a sound preset is basically just changing 9 (or so) sounds on that Style tab. It's a matter of one minute. And changing those afterwards to other sounds takes just as long.

**Comment by NeverSinkDev** [comment]
Not quite an issue. We'll see how we can improve the situation, but for now we implemented sound previewing and might add more features in the future. 

Closed for now.
