### ISSUE TITLE
No easy way to install sound packs into filters

### ISSUE THREAD

**Issue by SineSwiper** [NeverSinkDev/NeverSink-Filter#91]
With many people putting out their own sound packs on Reddit and elsewhere, there should be a easier way to install these sound packs into existing FilterBlade filters.  Perhaps a ZIP file with all of the sounds and a custom FilterBlade config file to detail where it should go.

**Comment by NeverSinkDev** [comment]
We're looking into it!

I can't give a solid ETA, but I'm looking into advanced ways to support sound pack generation.

**Comment by Tobnac** [comment]
There are basically 3 cases here:

Case 1: Someone provides sound files and a .filter file, in which they are already implemented.
In this case you'd have a problem because you can't import that filter into FilterBlade (well), so it already stops there.

Case 2: Someone provides just the sound files: With the provided NS file names.
In this case you can just select the "CustomSounds" filter style (or preset) and you're basically done. As long as all the sounds have the template file names, it should work right away.

Case 3: Someone provides just the sound files: With more sounds or different names.
For this case, you can use the Custom Sound "Manage" function on FilterBlade.
Wherever you can edit sounds, you can select custom and click Manage. There, you can just upload all the sound files. This allows you to select them from a dropDown menu and also hear the sound itself while customizing.
We can't know where we should put each sound, so I can really recommend the usage of the "Style" tab for this one to mass-edit every occurrence of e.g. Exalted sound 6 with e.g. BexPopSound.mp3.

I hope this helps you out, sorry for the very delayed response.
