### ISSUE TITLE
DisableDropSound True/False

### ISSUE THREAD

**Issue by zaafar** [NeverSinkDev/NeverSink-Filter#93]
Looks like DisableDropSound doesn't accept "True". Path of exile just ignores it
Is there a reason for writing True in front of DisableDropSound?

**Comment by Tobnac** [comment]
Habit?

We didnt deal much with the DisableDropSound identifier. You can write literally anything after it, PoE doesn't care. We just implemented it as just another boolean ident, just to be able to use existing syntax parsing/verification, even tho "DisableDropSound False" wont work. Its just about having the DDS line or not. We'll probably do it right when we finally fully implement it into FilterBlade, but right now there are other priorities...

**Comment by NeverSinkDev** [comment]
To expand upon tobnac's answer: 

That command was implemented in the middle of bestiary and there were no details on how it was initially implemented. 

That's why we stuck to the first working and easiest to implement version, since it was a hotfix (in that patch the bestiary nets, annoyed everyone)
